### ISSUE TITLE
The training is very slow

### ISSUE THREAD

**Issue by tinggh** [AILab-CVC/UniRepLKNet#15]
My train seems too slow comoared with ConvNeXt and SwinTransformer

**Comment by invictus717** [comment]
Could you please specify your training situation? Could you let me know if you have already installed the faster implementation of the large-kernel ConvNet in our repository?

https://github.com/AILab-CVC/UniRepLKNet#use-an-efficient-large-kernel-convolution-with-pytorch

**Comment by tinggh** [comment]
The UniRepLKNet backbone is used in an segmentation task. The the faster implementation of large-kernel ConvNet is not used. This may be the cause of the my problem and I'll have a try.

**Comment by invictus717** [comment]
Exactly, the faster implementation may be important to semantic segmentation tasks while a big batch size is utilized.
