### ISSUE TITLE
论文里面的一个问题

### ISSUE THREAD

**Issue by EveningLin** [AILab-CVC/UniRepLKNet#4]
![image](https://github.com/AILab-CVC/UniRepLKNet/assets/110521494/580dddf7-900c-4de7-84f7-cc42fbbaed5d)
![image](https://github.com/AILab-CVC/UniRepLKNet/assets/110521494/d9405355-6bb5-4eae-90fd-895628084b56)
是不是写错了（5，5，3，3）？

**Comment by EveningLin** [comment]
![image](https://github.com/AILab-CVC/UniRepLKNet/assets/110521494/a5bfa021-0817-4220-b635-54005ea6b664)
请问这里droppath为什么要递增呢

**Comment by DingXiaoH** [comment]
1. 是论文里这个数字写错了，请以code为准。
2. 可以想象，kernelsize为k的时候，kernel两个边（如最左边到最右边）之间的距离是k-1个点，dilation=r使得这个距离膨胀到了r倍，所以是(k-1)r，再加上中间点，kernelsize就是(k-1)r+1
3. 这是至少从Swin开始，可能更早，的common practice

**Comment by zpc-666** [comment]
> ![image](https://private-user-images.githubusercontent.com/110521494/287450606-a5bfa021-0817-4220-b635-54005ea6b664.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1ODQyODAsIm5iZiI6MTcwMzU4Mzk4MCwicGF0aCI6Ii8xMTA1MjE0OTQvMjg3NDUwNjA2LWE1YmZhMDIxLTA4MTctNDIyMC1iNjM1LTU0MDA1ZWE2YjY2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQwOTQ2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjBmYTg0NzBjNTQ3YjZhNjU3YjM1MzFhZjI4NmJmNjQyYmI1YjQ3YzI5YzI0OWFmZjU3OWFkODA4NGY4N2I0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G3_gxNyREN525h5J2_hikuGw3ESiguNYBKRlt3DvZIU) 请问这里droppath为什么要递增呢

这个地方是Deep Networks with Stochastic Depth这篇提出来的，这里pl是存活率，等于1-dp_rate
![1703584131679](https://github.com/AILab-CVC/UniRepLKNet/assets/55796038/ec8e086e-d3df-40f3-b2fe-04e342676189)
