### ISSUE TITLE
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.4\\bin\\nvcc.exe'

### ISSUE THREAD

**Issue by 15023520700** [AILab-CVC/UniRepLKNet#6]
no suitable conversion function from "__half" to "float" existsfast_math.h(741): error: no suitable conversion function from "__half" to "float" exists

**Comment by invictus717** [comment]
Please refer to the doc and set up the environment. It's also suggested to run the experiments on Linux.
