### ISSUE TITLE
您好，无法使用timm创建模型

### ISSUE THREAD

**Issue by xzx0554** [AILab-CVC/UniRepLKNet#9]
您好！无论是model = timm.create_model('unireplknet_l', num_classes=num_classes_of_your_task, in_22k_pretrained=True)还是您在点云示例代码中使用的model = timm.create_model('unireplknet_small')，都提示Unknown model 。我已排除网络问题，请问是什么情况？

**Comment by DingXiaoH** [comment]
需要先
from unireplknet import *
然后再create_model
